language: python
python:
  - "3.6.6"

services: postgresql

env:
  global:
# - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="bundesliga_site.settings"
  - PYTHONPATH="/home/travis/build/evbeda/imahunga"
  - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travisdb;' -U postgres
  - python manage.py migrate
  - coverage erase

script:
 - coverage run manage.py test

after_success:
  - coveralls