# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0003_auto_20181008_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=200)),
                ('discount_code', models.CharField(max_length=500)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.Event')),
            ],
        ),
    ]
