# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0004_discountcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='event_id',
            new_name='event',
        ),
    ]
