# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('value_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventTicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id_eb', models.CharField(max_length=200, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='MemberDiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=200)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.DiscountCode')),
            ],
        ),
        migrations.CreateModel(
            name='StatusMemberDiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bundesliga_app.Discount')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.Event')),
            ],
            bases=('bundesliga_app.discount',),
        ),
        migrations.CreateModel(
            name='TicketDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bundesliga_app.Discount')),
                ('ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.EventTicketType')),
            ],
            bases=('bundesliga_app.discount',),
        ),
        migrations.AddField(
            model_name='memberdiscountcode',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.StatusMemberDiscountCode'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.Discount'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.DiscountType'),
        ),
    ]
