# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
