# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='event_id',
            new_name='event',
        ),
    ]
