# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 14:18
from __future__ import unicode_literals

from django.db import migrations


def fill_discount_code_status(apps, schema_editor):
    StatusMemberDiscountCode = apps.get_model(
        'bundesliga_app', 'StatusMemberDiscountCode')
    StatusMemberDiscountCode.objects.create(
        name='Unknown'
    )
    StatusMemberDiscountCode.objects.create(
        name='Used'
    )
    StatusMemberDiscountCode.objects.create(
        name='Canceled'
    )


def fill_discount_type(apps, schema_editor):
    DiscountType = apps.get_model(
        'bundesliga_app', 'DiscountType')
    DiscountType.objects.create(
        name='Event'
    )
    DiscountType.objects.create(
        name='Ticket Type'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_discount_code_status),
        migrations.RunPython(fill_discount_type),
    ]
