# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0002_auto_20181106_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketDiscount',
            new_name='TicketTypeDiscount',
        ),
    ]
