# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0005_auto_20181024_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='eb_event_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
