# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0006_discountcode_eb_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id_eb', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='discount',
            name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='eventtickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.Event'),
        ),
        migrations.AddField(
            model_name='discount',
            name='ticket_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.EventTicketType'),
            preserve_default=False,
        ),
    ]
