# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0007_auto_20181025_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='event',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='discount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.Discount'),
            preserve_default=False,
        ),
    ]
