# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0009_auto_20181029_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusDiscountCode',
            new_name='StatusMemberDiscountCode',
        ),
    ]
