# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 17:05
from __future__ import unicode_literals

from django.db import migrations


def fill_discount_code_status(apps, schema_editor):
    StatusMemberDiscountCode = apps.get_model(
        'bundesliga_app', 'StatusMemberDiscountCode')
    StatusMemberDiscountCode.objects.create(
        name='Unknown'
    )
    StatusMemberDiscountCode.objects.create(
        name='Used'
    )
    StatusMemberDiscountCode.objects.create(
        name='Canceled'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0010_auto_20181029_1016'),
    ]

    operations = [
        migrations.RunPython(fill_discount_code_status),
    ]
