# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def fill_discount_type(apps, schema_editor):
    DiscountType = apps.get_model(
        'bundesliga_app', 'DiscountType')
    DiscountType.objects.create(
        name='Event'
    )
    DiscountType.objects.create(
        name='Ticket Type'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bundesliga_app', '0011_auto_20181105_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.Event'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.EventTicketType'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bundesliga_app.DiscountType'),
            preserve_default=False,
        ),
        migrations.RunPython(fill_discount_type),
    ]
